### PR TITLE
Postgres schemas support

### PR DESCRIPTION
**Pull request by williamabreu**
#### 📝 Description

This PR adds schema segregation support for Postgres databases, looking towards a microservices migration model.

#### 🛠️ Changes

- Added schema on orm configuration (3b5e25d)
- Removed useless root aggregate (a7f6ddf, 60a7b16)
- Added legacy support to use without schemas (22dafea)

### CODE REVIEW

**Review by andreyrcdias — COMMENTED** [review]
Nothing to point out about the changes made here.

How would it work if I didn't want to use schema? would be `public` as default?

**Comment by williamabreu** [comment]
@andreyrcdias I didn't set the default schema, nice suggestion!

**Comment by williamabreu** [comment]
@andreyrcdias setting the default to public, it's necessary to use public schema prefix for all queries or foreign keys definitinos, such as is made for custom schemas names. In this way, I don't think setting the default public could be useful what do you think about it?

**Review by andreyrcdias — COMMENTED** [review]
LGTM.

Nice job @williamabreu 👌🏽

**Pull request merged**
